import { WhoAmICardOptionType } from "@/types";

export const gameData: WhoAmICardOptionType[] = [
  {
    category: "Foglalkozások",
    color: "#f0710d",
    data: [
      ["Tanár", "Ügyvéd", "Ács"],
      ["Orvos", "Villanyszerelő", "Író"],
      ["Szakács", "Programozó", "Rendőr"],
      ["Építész", "Taxisofőr", "Pincér"],
      ["Mérnök", "Politikus", "Színész"],
      ["Fogorvos", "Üzletember", "Búvár"],
      ["Gépész", "Tűzoltó", "Újságíró"],
      ["Biológus", "Pilóta", "Festő"],
      ["Takarító", "Patikus", "Szobrász"],
      ["Fodrász", "Kertész", "Könyvtáros"],
      ["Színész", "Rendező", "Zongorista"],
      ["Könyvelő", "Gyógytornász", "Pszichológus"],
      ["Ügyintéző", "Nyelvész", "Lakatos"],
      ["Pék", "Villamosvezető", "Tudós"],
      ["Vízipólós", "Kémikus", "Jogi asszisztens"],
      ["Bolti eladó", "Szállítómunkás", "Politológus"],
      ["Tengerész", "Szoftverfejlesztő", "Lovas oktató"],
      ["Futballista", "Magánnyomozó", "Teológus"],
      ["Vízvezeték-szerelő", "Állatorvos", "Drámaíró"],
      ["Balett-táncos", "Geológus", "Projektmenedzser"],
      ["Történész", "Optikus", "Járművezető"],
      ["Operaénekes", "Irodalmár", "Fotós"],
      ["Teherautó-sofőr", "Bankár", "Ornitológus"],
      ["Fémmegmunkáló", "Korcsolyázó", "Zeneszerző"],
      ["Szobrász", "Burkoló", "Korrektor"],
      ["Matematikus", "Erdész", "Testnevelő tanár"],
      ["Régész", "Költő", "Vígjátékíró"],
      ["Vadász", "Zeneoktató", "Műszaki rajzoló"],
      ["Tanácsadó", "Farmgazda", "Sakkjátékos"],
      ["Sziklamászó", "Énektanár", "Mérnök"],
    ],
  },
  {
    category: "Nemzetiségek",
    color: "#970d86",
    data: [
      ["Japán", "Mexikói", "Norvég"],
      ["Kínai", "Francia", "Német"],
      ["Olasz", "Egyiptomi", "Spanyol"],
      ["Török", "Kanadai", "Argentín"],
      ["Indiai", "Ausztrál", "Görög"],
      ["Dél-koreai", "Orosz", "Amerikai"],
      ["Brazil", "Pakisztáni", "Holland"],
      ["Svéd", "Dán", "Thaiföldi"],
      ["Lengyel", "Izlandi", "Szerb"],
      ["Cseh", "Maláj", "Fülöp-szigeteki"],
      ["Új-zélandi", "Ír", "Vietnámi"],
      ["Szaúdi", "Osztrák", "Román"],
      ["Skót", "Perui", "Algériai"],
      ["Portugál", "Iraki", "Szlovén"],
      ["Belga", "Finn", "Ciprusi"],
      ["Magyar", "Venezuelai", "Maláj"],
      ["Indonéz", "Szlovák", "Kolumbiai"],
      ["Mongol", "Kubai", "Szingapúri"],
      ["Horvát", "Ciprusi", "Jordán"],
      ["Grúz", "Nigériai", "Ománi"],
      ["Marokkói", "Észt", "Szenegáli"],
      ["Tunéziai", "Ukrajnai", "Bahreini"],
      ["Lett", "Afganisztáni", "Kuvaiti"],
      ["Belorusz", "Nepáli", "Kenyai"],
      ["Bangladesi", "Costa Rica-i", "Hondurasi"],
      ["Szíriai", "Elefántcsontparti", "Madagaszkári"],
      ["Bahamai", "Panamai", "Botswana-i"],
      ["Libanoni", "Sierra Leone-i", "Maldiv-szigeteki"],
      ["Ruandai", "Mongóliai", "Türkmenisztáni"],
      ["Kambodzsai", "Cseh", "Kanadai"],
    ],
  },
  {
    category: "Kitalált szereplők",
    color: "#0047AB",
    data: [
      ["Sherlock Holmes", "Pikachu", "Wonder Woman"],
      ["Darth Vader", "James Bond", "Garfield"],
      ["Harry Potter", "Lara Croft", "SpongyaBob"],
      ["Iron Man (Vasember)", "Csubakka", "Jancsi (Jancsi és Juliska)"],
      ["Mickey Mouse", "Legolas", "Popeye"],
      ["Superman", "Gandalf", "Tapsi Hapsi"],
      ["Bart Simpson", "Elsa (Jégvarázs)", "Hulk"],
      ["Aladin", "Batman", "Ariel (A kis hableány)"],
      ["Piroska", "Shrek", "Woody (Toy Story)"],
      ["Zorro", "Elsa (Jégvarázs)", "Alíz (Csodaországban)"],
      ["Frodo", "Pókember", "Szimba"],
      ["Scooby-Doo", "Rapunzel", "Tarzan"],
      ["Drakula", "Aranyhaj", "Obi-Wan Kenobi"],
      ["Télapó", "Merida (Merida, a bátor)", "Wile E. Coyote"],
      ["Donald kacsa", "Captain America", "Gollam"],
      ["Tigris (Micimackó)", "Balu kapitány", "Peter Pan"],
      ["Pumukli", "Hannibal", "Pocahontas"],
      ["Hermione Granger", "Eric Cartman", "Buzz Lightyear"],
      ["Thor", "Jafar", "Pinokkió"],
      ["Joker", "A Kis Herceg", "Asterix"],
      ["Tintin", "Hamupipőke", "Dr. Watson"],
      ["Woody Woodpecker", "Perselus Piton", "Ron Weasley"],
      ["Homer Simpson", "Micimackó", "Meg Ryan"],
      ["Frakk", "Ursula (Ariel)", "Volt"],
      ["Sancho Panza", "Mulan", "Barbie"],
      ["MacGyver", "Pán Péter", "Hercule Poirot"],
      ["Goofy", "Bambi", "Fiona"],
      ["Herkules", "Szörnyella de Frász", "Törpilla"],
      ["SpongyaBob", "Robin Hood", "Füles"],
      ["Willy Wonka", "Malacka", "Gandalf"],
      ["Garfield", "Csipkerózsika", "Tapmancs"],
    ],
  },
  {
    category: "Ismert emberek",
    color: "#00695c",
    data: [
      ["Julius Cézár", "Madonna", "Mark Zuckerberg"],
      ["Bill Gates", "Charlie Chaplin", "Napóleon"],
      ["Lionel Messi", "George Washington", "Kern András"],
      ["Leonardo DiCaprio", "Stohl András", "Freddie Mercury"],
      ["Pelé", "Shakespeare", "Cristiano Ronaldo"],
      ["Albert Einstein", "Marilyn Monroe", "Leonardo da Vinci"],
      ["Michelangelo", "Lady Gaga", "Elvis Presley"],
      ["Usain Bolt", "Pablo Picasso", "Oprah Winfrey"],
      ["Mahatma Gandhi", "Angelina Jolie", "Martin Luther King Jr."],
      ["Coco Chanel", "Korda Gyuri bácsi", "Lewis Hamilton"],
      ["Brad Pitt", "Mozart", "Bob Marley"],
      ["Zámbó Jimmy", "Szinetár Dóra", "Bartók Béla"],
      ["Barack Obama", "Elon Musk", "József Attila"],
      ["Rákóczi Ferenc", "Winston Churchill", "Bruce Lee"],
      ["Sebestyén Balázs", "Buddha", "Barack Obama"],
      ["Steve Jobs", "Helena Bonham Carter", "Beethoven"],
      ["Sigmund Freud", "Zuzana Čaputová", "Petőfi Sándor"],
      ["Nikola Tesla", "Vadon Jani", "Emma Watson"],
      ["Isaac Newton", "Kolumbusz Kristóf", "Oprah Winfrey"],
      ["Walt Disney", "Oroszlán Szonja", "Cleopatra"],
      ["Ördög Nóra", "Salvador Dalí", "Azahriah"],
      ["Charles Darwin", "Michael Jordan", "Rúzsa Magdi"],
      ["Arany János", "Thomas Edison", "Arnold Schwarzenegger"],
      ["Marie Antoinette", "Vladimir Lenin", "Dalai Lama"],
      ["Varga Izabella", "Coco Chanel", "Frank Sinatra"],
      ["Malala Yousafzai", "Till Attila", "Yuri Gagarin"],
      ["Hernádi Judit", "Alfred Hitchcock", "Grace Kelly"],
      ["Nikolaus Copernicus", "Neil Armstrong", "Keresztes Ildikó"],
      ["Karl Lagerfeld", "Anne Frank", "Alföldi Róbert"],
    ],
  },
];
